// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnPDnwn-2aakqNmtVwbBEScNvRKvHBuRg',
    appId: '1:735971227383:android:ae7f2dc6bd2cf7daf4c5f2',
    messagingSenderId: '735971227383',
    projectId: 'secretarial',
    storageBucket: 'secretarial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcOyo3zuSriJV0IYCvb-YOiTWKzn3rtVo',
    appId: '1:735971227383:ios:f19234042e8f781cf4c5f2',
    messagingSenderId: '735971227383',
    projectId: 'secretarial',
    storageBucket: 'secretarial.appspot.com',
    iosBundleId: 'com.secretarialapp.dose.asml.www.secretarialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhl_psyoCVAqSQ8Zk1PdxMFABndWIvwww',
    appId: '1:735971227383:web:905d06c0aa0b0526f4c5f2',
    messagingSenderId: '735971227383',
    projectId: 'secretarial',
    authDomain: 'secretarial.firebaseapp.com',
    storageBucket: 'secretarial.appspot.com',
    measurementId: 'G-L1YJHJPBER',
  );
}
