/// Flutter icons Icon_app
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icon_app
///      fonts:
///       - asset: fonts/Icon_app.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Icon_app {
  Icon_app._();

  static const _kFontFam = 'Icon_app';
  static const String? _kFontPkg = null;

  static const IconData close = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t4t = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_italic = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_list_bulleted = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_list_numbered = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_strikethrough = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData format_underlined = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData functions = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_outline__1_ = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_outline = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insert_link = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mode = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData title = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibility = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_location = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle_outline = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_box = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_alert = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_6 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_5 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData build = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_enhance = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_front = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite_border = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error_outline = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knee_005 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kidney_004 = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fetus_003 = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diabetes_test_002 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spray_nasal_018 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orthopdie_019 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardio = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dents__2_ = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData en_pensant = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foetus = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hygie = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData le_genou = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newborn_006 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opthalmologist_007 = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData le_genre = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f328937c5d4fc0384092699327f476e8 = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin6 = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin5 = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin4 = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin3 = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spin2 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exercise_weights = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pharmacy_dark = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agriculture = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virus_alt_dark = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pharmacy_alt = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electricity = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electricity_dark = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pharmacy_alt_dark = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virus_alt = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ventilator_dark = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_quarantine = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ppe_santizer_alt = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simple_logo_dark = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ppe_santizer_alt_dark = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finance_dept_dark = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_quarantine__dark = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finance_dept = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poison_dark = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bandage_adhesive_dark = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bandage_adhesive = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poison = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fever = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData defibrilator = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pharmacy = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virus = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pharmacy__dark = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coronary_care_unit = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coronary_care_unit_dark = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palliative_care = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ventilator = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe_vaccine_dark = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palliative_care_dark = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cold_chain = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cold_chain_dark = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData observation_dark = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe_vaccine = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData observation = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biochemistry_laboratory_dark = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_dark = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe_dark = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surgical_sterilization = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blood_a_p = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inpatient_dark = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData surgical_sterilization_dark = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social_work = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inpatient = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biochemistry_laboratory = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i_exam_qualification_dark = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData social_work_dark = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simple_logo = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i_exam_qualification = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_dark = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zz4 = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lungs_008 = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wr6 = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData werewr = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData we22 = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ophtalmologiste = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r3 = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orthophonie = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dw8 = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dw5 = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData z5 = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender_012 = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stethoscope_1013 = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reins = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData we3 = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wd5 = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData er5t = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData er35 = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData erewt8 = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ert8 = IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData erer5 = IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData we6 = IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData we5 = IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic3 = IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r3r2 = IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xs5 = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData veterinary_014 = IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teeth_015 = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poumons = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thinking_016 = IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_center_focus = IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soin_des_cheveux = IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stethoscope = IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oreille_017 = IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rein = IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nouveau_nee = IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microscope_4_001 = IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardio_1_001 = IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData veterinaire = IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test_de_diabete = IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accueil = IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendrier = IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lhistoire = IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magazinn = IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData utilisateur = IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_alt = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xf0e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_empty = IconData(0xf0e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_empty = IconData(0xf0e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_alt = IconData(0xf0f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_right = IconData(0xf105, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply = IconData(0xf112, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code_1 = IconData(0xf121, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply_all = IconData(0xf122, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention_alt = IconData(0xf12a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up_alt = IconData(0xf164, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down_alt = IconData(0xf165, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_alt = IconData(0xf1e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off = IconData(0xf1f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off_empty = IconData(0xf1f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus = IconData(0xf221, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars = IconData(0xf222, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mercury = IconData(0xf223, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender = IconData(0xf224, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender_alt = IconData(0xf225, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus_double = IconData(0xf226, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars_double = IconData(0xf227, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus_mars = IconData(0xf228, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars_stroke = IconData(0xf229, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars_stroke_v = IconData(0xf22a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars_stroke_h = IconData(0xf22b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portrait = IconData(0xf3e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbbell = IconData(0xf44b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football_ball = IconData(0xf44e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData golf_ball = IconData(0xf450, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hockey_puck = IconData(0xf453, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quidditch = IconData(0xf458, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dolly_flatbed = IconData(0xf474, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_medical = IconData(0xf477, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_medical_alt = IconData(0xf478, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_aid = IconData(0xf479, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_alt = IconData(0xf47d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_symbol = IconData(0xf47e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card_alt = IconData(0xf47f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes_medical = IconData(0xf481, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pallet = IconData(0xf482, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pills = IconData(0xf484, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prescription_bottle = IconData(0xf485, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prescription_bottle_alt = IconData(0xf486, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smoking = IconData(0xf48d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syringe_1 = IconData(0xf48e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablets = IconData(0xf490, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer = IconData(0xf491, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vial = IconData(0xf492, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vials = IconData(0xf493, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warehouse = IconData(0xf494, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weight = IconData(0xf496, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_ray = IconData(0xf497, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hands_helping = IconData(0xf4c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_carry = IconData(0xf4ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggy_bank = IconData(0xf4d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ribbon = IconData(0xf4d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bezier_curve = IconData(0xf55b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bong = IconData(0xf55c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cocktail = IconData(0xf561, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_martini_alt = IconData(0xf57b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air_freshener = IconData(0xf5d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_alt = IconData(0xf5d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atom = IconData(0xf5d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bone = IconData(0xf5d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_reader = IconData(0xf5da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brain = IconData(0xf5dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
